# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Variable": "00_autodiff.ipynb",
         "create_constant_tensor": "00_autodiff.ipynb",
         "create_zero_tensor": "00_autodiff.ipynb",
         "create_ones_tensor": "00_autodiff.ipynb",
         "get_shape": "00_autodiff.ipynb",
         "generate_all_indices": "00_autodiff.ipynb",
         "Tensor": "00_autodiff.ipynb",
         "Module": "01_module.ipynb",
         "Linear": "01_module.ipynb",
         "Dense": "01_module.ipynb"}

modules = ["autodiff.py",
           "module.py"]

doc_url = "https://bwolfson97.github.io/nn_from_scratch/"

git_url = "https://github.com/bwolfson97/nn_from_scratch/tree/main/"

def custom_doc_links(name): return None
